import { DocumentSnapshot } from 'firebase-functions/lib/providers/firestore';
import { config, Change, EventContext } from 'firebase-functions';
import { firestore } from 'firebase-admin';
const stripe = require("stripe")(config().stripe.key);

export class PaymentHelper {
  static newPayment(fs: firestore.Firestore) {
    return async (snapshot: DocumentSnapshot, context: EventContext) => {

      const payment = snapshot.data();

      if (payment.paymentType === 'token') {
        const charge = {
          amount: fee * 100, // be sure to calculate the fee yourself; don't trust the client!
          currency: 'gbp',
          description: 'Some charge',
          source: payment.token.id, // token generated by Stripe.js
          receipt_email: payment.token.email
        };
      }
    }
  }
}
